config/routes.rb
Rails.application.routes.draw do

  resources :genres

  resource :session
  get 'signin'=> 'sessions#new'
  get 'signup'=> 'users#new'
   resources :users

  root "movies#index"
  resources :movies do
    resources :reviews
    resources :favorites
  end

end

app/models/genre.rb
class Genre < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true

  has_many :characterizations,dependent: :destroy
  has_many :movies, through: :characterizations


  
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
    before_action :require_signin, except: [:show, :index]
    before_action :require_admin, except: [:show, :index]


    def index
      @genres = Genre.all
    end

    def show
      @genre = Genre.find(params[:id])
      @movies= @genre.movies
         end

    def edit
      @genre = Genre.find(params[:id])
    end

    def update
      @genre = Genre.find(params[:id])
      if @genre.update(genre_params)
        redirect_to @genre, notice: "Genre successfully updated!"
      else
        render :edit
      end
    end

    def new
      @genre = Genre.new
    end

    def create
      @genre = Genre.new(genre_params)
      if @genre.save
        redirect_to @genre, notice: "Genre successfully created!"
      else
        render :new
      end
    end

    def destroy
      @genre = Genre.find(params[:id])
      @genre.destroy
      redirect_to genres_url, alert: "Genre successfully deleted!"
    end

    private

    def genre_params
      params.require(:genre).permit(:name)
    end

  end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <%= render "shared/errors", object: @genre %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </li>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", genres_path, class: 'button' %>
    </p>
        </ol>
  </fieldset>
<% end %>

app/views/genres/_movie_index.html.erb
<ul>
<li>
  <article class="movie" id="<%= dom_id(movie) %>">
    <header>
      <%= image_for(movie) %>
      <h2><%= link_to movie.title, movie %> (<%= movie.released_on.year %>)</h2>
      <h3><%= movie.cast %></h3>
    </header>
    <p>
      <%= truncate(movie.description, length: 150, separator: ' ') %>
    </p>
    <table>
      <tr>
        <th>Rating</th>
        <td><%= movie.rating %></td>
      </tr>
      <tr>
        <th>Duration</th>
        <td><%= movie.duration %></td>
      </tr>
      <tr>
        <th>Total Gross</th>
        <td><%= format_total_gross(movie) %></td>
      </tr>
    </table>
    <footer>
    </footer>
  </article>
</li>
</ul>

app/views/genres/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @genre.name %></h1>
</header>

<%= render 'form' %>

app/views/genres/index.html.erb
<ul id="movies">
  <% @genres.each do |genre| %>
    <li>
        <h3><%= link_to genre.name, genre %> </h3>
    </li>
  <% end %>
</ul>

<nav>
  <%= link_to 'New Genre', new_genre_path, class: 'button' %>

</nav>

app/views/genres/new.html.erb
<header id="content-header">
  <h1>Create a New Genre</h1>
</header>

<%= render 'form' %>

app/views/genres/show.html.erb
<article id="genre" class="movie">
  <header>
    <h1><%= @genre.name %></h1>
    <%=	 pluralize(@movies.size,'movie')%>
    <h3>Movies</h3>
    <ul>
      <% @movies.each do |movie| %>
          <ul>
            <li>
              <article class="movie" id="<%= dom_id(movie) %>">
                <header>
                  <%= image_for(movie) %>
                  <h2><%= link_to movie.title, movie %> (<%= movie.released_on.year %>)</h2>
                  <h3><%= movie.cast %></h3>
                </header>
                <p>
                  <%= truncate(movie.description, length: 150, separator: ' ') %>
                </p>
                <table>
                  <tr>
                    <th>Rating</th>
                    <td><%= movie.rating %></td>
                  </tr>
                  <tr>
                    <th>Duration</th>
                    <td><%= movie.duration %></td>
                  </tr>
                  <tr>
                    <th>Total Gross</th>
                    <td><%= format_total_gross(movie) %></td>
                  </tr>
                </table>
                <footer>
                </footer>
              </article>
            </li>
          </ul>

      <% end %>
    </ul>

    <footer>
    <nav>
      <% if current_user_admin? %>
          <%= link_to 'All Genres', genres_path, class: 'button' %>

          <%= link_to 'Edit', edit_genre_path(@genre), class: 'button' %>
          <%= link_to 'Delete', @genre,
                      class: 'button',
                      method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    </nav>
  </footer>
</header>
</article>