config/routes.rb
Rails.application.routes.draw do

  resources :genres

  resource :session
  get 'signin'=> 'sessions#new'
  get 'signup'=> 'users#new'
   resources :users

  root "movies#index"
  resources :movies do
    resources :reviews
    resources :favorites
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_movies, through: :favorites, source: :movie


  scope :by_name, -> { order(:name) }
  scope :not_admins, -> { by_name.where(admin: false) }




  validates :name, presence:  true
  validates :email, presence: true, format: /\A\S+@\S+\z/, uniqueness: {case_sensitive: false}
  validates :password, length: { minimum: 10, allow_blank: true }
  validates :username, presence: true, format: /\A[A-Z0-9]+\z/i, uniqueness: {case_sensitive: false}

  def self.orderedd
    order(id: :desc)
  end



  def self.ordereda
    order(id: :asc)
  end


  def self.authenticate(email_or_username, password)
    user = User.find_by(email: email_or_username) || User.find_by(username: email_or_username)
    user && user.authenticate(password)
  end




  def gravatar_id
    Digest::MD5::hexdigest(email.downcase)
  end






end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.not_admins
end
=begin
  def index
    @users = User.order("#{params[:sort_param]}")



    #@users = User.all.orderedd
    #@usersn = User.all.ordereda
  end
=end
  def order
  params[:sort_param] = %w{name created_at id}.include?(params[:sort_param]) ? params[:sort_param] : 'id'
  params[:sort_param2] = %w{name created_at id}.include?(params[:sort_param2]) ? params[:sort_param2] : 'id'

  if params[:sort_params]
    @users = User.order "#{params[:sort_param]} ASC"
  else
    params[:sort_params2]
    @users = User.order "#{params[:sort_param2]} DESC"
  end
  end



  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
    @favorite_movies = @user.favorite_movies
  end

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Thanks for signing up!'
    else
      render :new

    end
  end
  def edit
  #@user = User.find(params[:id])
  end
  def update
    #@user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'Account successfully updated!'
    else
      render :edit
    end
  end
  def destroy

      @user = User.find(params[:id])
      @user.destroy
     # session[:user_id] = nil # Puisque c'est l'admin qui est connecté
      redirect_to root_url, alert: "Account successfully deleted!"
    end
end

  private
def user_params
  params.require(:user).
      permit(:name, :email, :password, :password_confirmation, :username, :admin)
end
def require_correct_user
  @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end

app/helpers/users_helper.rb
module UsersHelper

  def profile_image_for_index(user)
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
    image_tag(url, alt: user.name, height: '32', width: '32')
  end

  def profile_image_for_show(user)
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
    image_tag(url, alt: user.name)
  end


  def profile_image_for(user, options={})
    size = options[:size] || 80
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}?s=#{size}"
    image_tag(url, alt: user.name)
  end


end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render "shared/errors", object: @user %>
    <fieldset>
      <ol>
        <li class="required">
          <%= f.label :name %>
          <%= f.text_field :name, autofocus: true %>
        </li>
        <li class="required">
          <%= f.label :email %>
          <%= f.email_field :email %>
        </li>
        <li class="required">
          <%= f.label :username %>
          <%= f.text_field :username, size: 40,
                           placeholder: "Alphanumeric characters only!" %>
        </li>
        <li class="required">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </li>
        <li class="required">
          <%= f.label :password_confirmation, 'Confirm Password' %>
          <%= f.password_field :password_confirmation %>
        </li>
      </ol>
      <p>

        <% if @user.new_record? %>
            <%= f.submit "Create Account" %>
        <% else %>
            <%= f.submit "Update Account" %>
        <% end %>


        <%= link_to "Cancel", users_path, class: 'button' %>
      </p>
    </fieldset>
<% end %>

app/views/users/edit.html.erb
<header id="content-header">
  <h1>Editing </h1>
</header>

<%= render 'form' %>

app/views/users/index.html.erb
<header id="content-header">
  <h1><%= pluralize(@users.size, 'User') %></h1>
</header>


<ul id="users">
  <% @users.each do |user| %>
      <li>
        <%= profile_image_for_index(user) %>
        <%=	 user.id %> |
        <%= link_to user.name, user %> |
        <%= user.created_at.strftime('Membre depuis le: %A/%d/%m/%Y à  %H:%M') %>
       </li>
        <% end %>
</ul>

<%= link_to '↑name', users_path(:sort_param => "name"), class: 'button' %>
<%= link_to '↑created_at', users_path(:sort_param => "created_at"), class: 'button' %>
<%= link_to '↑id', users_path(:sort_param => "id"), class: 'button' %>
<%= link_to 'id', users_path(:sort_param2 => "id"), class: 'button' %>

app/views/users/new.html.erb
<header id="content-header">
  <h1>Create a New User</h1>
</header>

<%=	 render 'form' %>

app/views/users/show.html.erb
<% content_for(:title, @user.name) %>
<%	 content_for :side do %>
    <% if @favorite_movies.any? %>
        <h3>Favorite Movies</h3>
        <ul>
          <% @favorite_movies.each do |movie| %>
              <li>
                <%= link_to movie.title, movie %>
              </li>
          <% end %>
        </ul>
    <% end %>
<%	 end %>


<%= profile_image_for_show(@user) %>

<h1>
  <%= @user.name %>
</h1>

<p>
  <%= mail_to @user.email, @user.email %>
</p>


<% if @reviews.any? %>
    <h3>Reviews</h3>
    <ol id="reviews">
      <% @reviews.each do |review| %>
          <li>
            <%= link_to review.movie.title, review.movie %>
            <span class="review"><%= pluralize(review.stars, 'star') %></span>
            <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
            <p>
              &quot;<%= review.comment %>&quot;
            </p>
          </li>
      <% end %>
    </ol>
<% end %>

<footer>
  <nav>
    <%	 if current_user?(@user) %>
    <%= link_to 'Edit Account',
                edit_user_path(@user),
                method: :get,
                class: 'button' %>
    <%	 end %>
    <%	 if current_user_admin? %>
    <%= link_to 'Delete Account',
                @user,
                method: :delete,
                data: { confirm: 'Are you sure you want to permanently delete your account?' },
                class: 'button' %>
        <%	 end %>
  </nav>
</footer>