config/routes.rb
Rails.application.routes.draw do

  resources :genres

  resource :session
  get 'signin'=> 'sessions#new'
  get 'signup'=> 'users#new'
   resources :users

  root "movies#index"
  resources :movies do
    resources :reviews
    resources :favorites
  end

end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2014
    <%= link_to 'Projet WebLove', 'https://sites.google.com/site/projetweblove/' %>
  </p>
  <p>
    Training.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to 'Flix', root_path %></h1>
    <nav>
      <p>
        <%	 if current_user_admin? %>
        <%= "Admin" %>
            <%	 end %>
        <% if current_user %>
            <%= link_to current_user.name, current_user, class: 'button' %>
            <%= link_to 'Sign Out',session_path, method: :delete, class: 'button' %>
            <%= link_to "Account Settings", edit_user_path(current_user), class: 'button' %>
        <% else %>
            <%= link_to 'Sign Up', signup_path, class: 'button' %>
            <%= link_to 'Sign In', signin_path, class: 'buton' %>
        <% end %>
      </p>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="movies">
        <%= link_to 'All Movies', movies_path, class: 'button' %>
      </li>
      <%	 if current_user_admin? %>
      <li class="create-movie">
        <%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
      </li>
          <% end %>
    </ul>
  </nav>
  <%= content_for (:side) %>
  </aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title%></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div id="wrapper">
  
  <%= render "layouts/flashes" %>
  
  <div id="container">
    <section id="sidebar">
      <%= render "layouts/sidebar" %>
    </section>
    <section id="content">
      <%= yield %>
    </section>
  </div>

</div>

<%= render "layouts/footer" %>

</body>
</html>